feature/RI-706
A2O-Dev/Webdriverio-Automatizaci-n pull request #8
Opened 2023-01-11 22:56 UTC by Lino1998

2023-01-12 15:31 UTC, davidAlmarazA2odev requested changes
Porfavor resolver los cambios solicitados

2023-01-12 15:31 UTC, cancioalmaraza2o commented on test/specs/tests/carousetest.ts
> +        //await browser.pause(8000)
Lineas 5 y 9-12

Código comentado no está permitido.

Borrar estas líneas de código si no están realizando ninguna acción

2023-01-12 15:31 UTC, cancioalmaraza2o commented on README.md
> +
Estos cambios son realmente necesarios?

Normalmente no se aceptan cambios que no afecten la funcionalidad

2023-01-12 15:31 UTC, davidAlmarazA2odev commented on test/specs/tests/navigation.test.ts
> +        const checkoursolutionButton = await $('=CHECK OUR SOLUTIONS')
Usar nombres de variables tipo lowerCamelCase, para esta línea ejemplo:

checkOurSolutionButton

Aplica este mismo concepto a todas las variables

2023-01-12 15:31 UTC, davidAlmarazA2odev commented on test/specs/tests/navigation.test.ts
> +})
Añade una linea vacía al final del archivo

2023-01-12 15:31 UTC, davidAlmarazA2odev commented on test/specs/tests/carousetest.ts
> +        const imagesappLink = await $('.premium-modal-trigger-text').$('div*=Images')
Para las variables de este archivo también usar lowerCamelCase

2023-01-12 15:50 UTC, Lino1998 commented on README.md
> +
Realmente no eliminando cambio.

2023-01-12 15:51 UTC, Lino1998 commented on test/specs/tests/carousetest.ts
> +        const imagesappLink = await $('.premium-modal-trigger-text').$('div*=Images')
Se realizo el cambio a las variacles creadas siguiendo el formato de lowerCamelCase
![image](https://user-images.githubusercontent.com/120578586/212114704-07f60ea5-79d4-44c6-ae1e-1a6fa795074f.png)

2023-01-12 15:53 UTC, Lino1998 commented on test/specs/tests/navigation.test.ts
> +        const checkoursolutionButton = await $('=CHECK OUR SOLUTIONS')
Se realizo los cambios a las variables para que sigan el formato lowerCamelCase
![image](https://user-images.githubusercontent.com/120578586/212114971-10cbca6d-87c2-41e0-b5b6-e74b68e49c7b.png)

2023-01-12 16:03 UTC, Lino1998 commented on test/specs/tests/carousetest.ts
> +        //await browser.pause(8000)
El codigo comentado fue removido

2023-01-13 12:45 UTC, davidAlmarazA2odev approved these changes
Approved

2023-01-13 12:45 UTC, cancioalmaraza2o commented on README.md
> +
Sigue existiendo el cambio, este archivo ya no debería mostrarse en el pull request si no está alterándose

2023-01-13 12:45 UTC, cancioalmaraza2o commented on test/specs/tests/carousetest.ts
> +        const imagesappLink = await $('.premium-modal-trigger-text').$('div*=Images')
Esta variable:
imagesappLink
Debería ser:
imagesAppLink

2023-01-13 12:45 UTC, cancioalmaraza2o commented on test/specs/tests/carousetest.ts
> +        //await browser.pause(8000)
El codigo comentado sigue mostrandose

2023-01-13 12:45 UTC, cancioalmaraza2o commented on README.md
> -# Webdriverio-Automatizaci-n
Nuevamente, no elimines este archivo, es un cambio innecesario.

2023-01-13 12:46 UTC, davidAlmarazA2odev commented
Code review aprobado, procediendo a mergear

2023-01-13 12:47 UTC, merged